spring.application.name=GenAiP04
spring.ai.google.genai.api-key=AIzaSyCnSrrNdcLc2x0HGRRVicfBbhn_Sb9okyk
spring.ai.google.genai.chat.options.model=${GEMINI_MODEL:gemini-2.5-flash-lite}

#for advisor activate and use for debugging
logging.level.org.springframework.ai.chat.client.advisor=DEBUG